YALB-611: Tabs component
yalesites-org/component-library-twig pull request #106
Opened 2022-07-09 23:10 UTC by ModulesUnraveled

## [YALB-611: Tabs component](https://yaleits.atlassian.net/browse/YALB-611)

### Description of work
- Creates the tabs component
- Fixes link underline position (for standard body text links - and supports a custom position for tabs)

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/molecules-tabs--tabs)

### Functional Review Steps
- [ ] Verify you can install the component with the CLI

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

2022-07-11 16:17 UTC, ahitson commented
Desktop looking good, but tabs should be centered.

Is there a way to look at the mobile version? Right now it's creating a bottom scroll bar.

2022-07-11 18:15 UTC, kara-franco approved these changes
Perfection! I really like the Heydon/Inclusive Components implementation, very easy to use with keyboard and/or screen reader. 

I noticed the bar in mobile view as well, I'll be sure to check back in after that is resolved for a final look, but for now, looks awesome!

2022-07-12 18:50 UTC, kara-franco requested changes
- [ ] Add `aria-controls` to the tab elements to better associate the tab to the tab panel. (Did some more research about tabs with Nick and adding aria-controls will help VoiceOver and JAWS users). 
<img width="487" alt="Screen Shot 2022-07-12 at 2 45 37 PM" src="https://user-images.githubusercontent.com/12991593/178571732-57b670c9-a2e0-4b88-9195-182b4f357812.png">

2022-07-12 18:53 UTC, miketullo95 commented
Will there be a control option for the tabs to have different width lines for the active tab? Currently, the width is fairly large but it would make sense if the site utilizes the thicker divider sizes like 6 or 8.

2022-07-20 14:50 UTC, ahitson commented
Much better. 
- Is that the correct icon variation? Seems thick.
- Can we add a color change hover state to the icon?

2022-07-20 21:44 UTC, kara-franco requested changes
Very small request after screen reader testing and talking with Nick! 

- [ ] Add `tabindex="0"` to the `<div>` with `role="tabpanel"`

This will help screen reader users get to the panel content when there are no focusable elements in the panel. 

<img width="1496" alt="Screen Shot 2022-07-20 at 5 38 26 PM" src="https://user-images.githubusercontent.com/12991593/180087153-e1f8a292-192e-42d4-86ff-d40ebf9ec7e2.png">

2022-07-21 11:10 UTC, ModulesUnraveled commented
@miketullo95 right now, no. It's thinner on mobile, and thicket on desktop. If we need to make it a configurable thing, we probably could. But since it changes at viewports it would be more difficult. Not off the table, just wanted to reply that no, currently it is not configurable.

@ahitson This is the same icon that's used in the main nav and stuff. HOWEVER, we are still using the thicker versions. We haven't implemented the pro icons yet, which are thinner. I'd like to update all of the icons in a stand-alone PR though so that when we check the visual regression results it'll be easier to verify that the icons are the only thing that change. (review will be easier)

... I think everything else has been addressed!

2022-07-21 14:35 UTC, ahitson approved these changes

2022-07-21 21:09 UTC, kara-franco requested changes
@ntay90 I checked the mobile view again and if a mobile user selects a tab that is near an arrow, the tab title remains off screen (I don't remember seeing this before). I would expect that if the tab title is selected, the entire title would move into view? 

**Horizontal (Landscape view) tabbing/switch control on mobile:**
<img width="671" alt="Screen Shot 2022-07-21 at 5 05 25 PM" src="https://user-images.githubusercontent.com/12991593/180315386-521feb6e-60e3-4705-b913-83a8bb637720.png">

**Vertical (Portrait view) tabbing/switch control on mobile:** 
<img width="283" alt="Screen Shot 2022-07-21 at 1 28 56 PM" src="https://user-images.githubusercontent.com/12991593/180315619-ffccf7e2-0458-4d19-b283-7bb4260f772d.png">

**Expected display when tab title is selected:**
<img width="277" alt="Screen Shot 2022-07-21 at 1 29 06 PM" src="https://user-images.githubusercontent.com/12991593/180315621-6aa724f4-2006-4883-a8cf-6154b63dd385.png">

2022-07-22 17:22 UTC, ntay90 commented
What do you think of the user's cursor changing to a grab cursor when hovered over the tab bar in overflow? This could indicate that the tab bar can be clicked and dragged. 

<img width="828" alt="Screen Shot of tab bar with grab cursor." src="https://user-images.githubusercontent.com/69398223/180491452-37c2c8bb-ac17-4fb4-834e-3c6be9eb6e10.png">

2022-07-22 17:28 UTC, ModulesUnraveled commented
@ntay90 Well, a mouse user **can't** actually click and drag. Scroll devices (touch on mobile phones, and laptop trackpads, for example) work, but actually clicking and dragging doesn't scroll the tabs. So I think I would get frustrated if I saw that icon, and wasn't able to perform that action.

For what it's worth, we have a ticket to revisit that functionality (a mouse user clicking and dragging) after doing some user testing, and getting feedback about whether that functionality is a high priority.

2022-07-24 11:20 UTC, ModulesUnraveled commented
@kara-franco I think I got the "move focused item into view" (whether by keyboard or mouse) nailed down.

2022-07-25 16:41 UTC, miketullo95 approved these changes

2022-07-26 16:49 UTC, ntay90 approved these changes

2022-07-26 17:01 UTC, callinmullaney requested changes
@ModulesUnraveled See code comments for technical suggested changes. 

Lastly, as a mouse user I found the tabs interaction to be a little frustrating with the REALLY LONG tabs navigation. My scroll wheel didn't allow me to quickly go through the list and click-and-drag (as you already mentioned) isn't a thing here. This resulted in me needing to click 20+ times on the arrows to reach the end. Obviously, this is an extreme edge case and the scenario where a tab group even has half as much tabs is probably slim. But it's something to consider.

2022-07-26 20:12 UTC, ModulesUnraveled commented on components/01-atoms/controls/base/control.twig
> +    {{- control__content -}}
Done

2022-07-26 20:12 UTC, ModulesUnraveled commented on components/02-molecules/tabs/_tabs.scss
> +  scroll-behavior: smooth;
Good point!

2022-07-26 20:39 UTC, ModulesUnraveled commented on components/02-molecules/tabs/tabs.twig
> +{% set tabs__base_class = 'tabs' %}
I refactored this to use add_attributes a bunch of places, and added a TODO with a link to a JIRA ticket I just created to address refactoring it to use the list and link components.

I'm going to go ahead and merge now, but we can talk more in that ticket, or here, or Slack if you notice something else glaring. Thanks for the review!

2022-07-26 21:01 UTC, merged

2022-07-26 21:01 UTC, callinmullaney reviewed
:+1: