YALB-1410: Bug: Accessibility (FE)- Color Contrast issues in automatic testing tools
yalesites-org/component-library-twig pull request #300
Opened 2023-09-26 12:49 UTC by dblanken-yale

## [YALB-1410: Bug: Accessibility (FE)- Color Contrast issues in automatic testing tools](https://yaleits.atlassian.net/browse/YALB-1410)

### Description of work
- Moves component theme to root div of the following components:
  - Grand Hero
  - Action Banner

### Testing Link(s)
- [x] Navigate to the [Action Banner Component Story](https://deploy-preview-300--dev-component-library-twig.netlify.app/iframe.html?args=&id=molecules-banners--action-banner)
- [x] Navigate to the [Grand Hero Component Story](https://deploy-preview-300--dev-component-library-twig.netlify.app/iframe.html?args=&id=molecules-banners--grand-hero-banner&viewMode=story)
- [x] Navigate to the [Global Theme Color Pairings](https://deploy-preview-300--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--global-theme-color-pairings)
- [x] Deployed Versions
  - [x] [Grand Hero](https://yalesites-org.github.io/component-library-twig/iframe.html?args=&id=molecules-banners--grand-hero-banner)
  - [x] [Action Banner](https://yalesites-org.github.io/component-library-twig/iframe.html?args=&id=molecules-banners--action-banner)

### Functional Review Steps
- [x] Verify the action banner and grand hero still look and feel like the deployed versions.
- [x] Verify that the global theme levers for the banner matches the currently deployed versions.

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify that WAVE, Axe, and any other checkers are now happy with the H2 background color for both components

2023-09-26 21:46 UTC, joetower requested changes
@dblanken-yale This looks great, awesome work!

I noticed one thing we should probably change: the element which gets the background-color property for the CTA Banner. 

For the CTA Banner, move the `background-color` from `cta-banner` to the `cta-banner__content-wrapper` so the background color isn't visible when the browser window is wider than the image.

https://github.com/yalesites-org/component-library-twig/assets/366413/79a045c3-7902-45a1-8684-f8f37f8d16b4


<img width="2540" alt="Screenshot 2023-09-26 at 4 44 45 PM" src="https://github.com/yalesites-org/component-library-twig/assets/366413/6f1b5e39-9312-4d9e-96d1-556cbbd8ee00">

The Grand Hero is totally fine as-is since the `grand-hero-banner` element's width is limited.

2023-09-26 22:06 UTC, joetower commented
@dblanken-yale On second thought, maybe we should leave the background-color where you have it and move the `max-width` and `margin` properties from `cta-banner__content-wrapper` element the to the `cta-banner` element: 

```
  max-width: tokens.$break-max-width;
  margin-inline-start: auto;
  margin-inline-end: auto;
```

It occurred to me that these width and margin properties being on the inner wrapping element were established in an earlier iteration of the component. Perhaps it makes more sense to make this max-width and margin similar to the Grand Hero. What are your thoughts?

2023-09-27 14:39 UTC, dblanken-yale commented
@joetower There we go; I like this a lot more.  Let me know what you think.

2023-09-27 14:46 UTC, joetower approved these changes
@dblanken-yale Awesome, yes, this is a much better approach. Thank you, Dave!

2023-09-28 15:59 UTC, kara-franco approved these changes
Fantastic work!! All approved on my end.

2023-09-29 19:36 UTC, merged