YALB-79: Text-with-image component
yalesites-org/component-library-twig pull request #44
Opened 2022-03-10 23:12 UTC by ModulesUnraveled

## [YALB-79: Text-with-image component](https://yaleits.atlassian.net/browse/YALB-79)

### Description of work
- Adds functionality bullet item
- Fixes this or that bullet item

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/tokens-breakpoints--breakpoints)

### Functional Review Steps
- [ ] Verify XYZ

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

2022-03-11 15:08 UTC, kara-franco commented on components/02-molecules/text-with-image/text-with-image.twig
> +          heading__level: '3',
Looking really good!! 

The subheading doesn't need to be semantically a heading, it's not a new section or subsection of the parent heading. 

For a screen reader user, having the dates as H3's will clutter their web rotor (a tool that they use pull out headings/landmarks/links in the DOM, shown below). 

<img width="847" alt="Screen Shot 2022-03-11 at 9 58 19 AM" src="https://user-images.githubusercontent.com/12991593/157893682-e0a1ed53-3a61-4ed3-b61f-df6c4b3f1f8a.png">

2022-03-11 18:30 UTC, kara-franco approved these changes

2022-03-11 18:36 UTC, kara-franco requested changes
Just need to update the subheading and all is looking good!

2022-03-11 18:49 UTC, ModulesUnraveled commented
@kara-franco I removed the "h3" tag so it won't show up as an "official" heading

2022-03-11 20:04 UTC, kara-franco approved these changes
Yay, looks (and sounds) great!

2022-03-14 14:21 UTC, ahitson commented
Will there be image options for this?

2022-03-15 21:31 UTC, callinmullaney approved these changes
@ModulesUnraveled This looks great to me. I didn't see anything that stood out to me that should be addressed. I really like the control options/variations for this component :tada:

2022-03-16 11:54 UTC, ModulesUnraveled commented
@ahitson I don't think there's anything for us to do on the frontend as far as aspect ratio goes. On the backend, we'll need to make sure we address it as a requirement. That's where the user would choose the crop ratio. But the frontend component should accommodate whatever choice they make.

2022-03-16 13:00 UTC, ahitson approved these changes

2022-03-16 20:00 UTC, merged