1) YALB-375: Alerts
yalesites-org/component-library-twig pull request #55
Opened 2022-03-29 11:46 UTC by ModulesUnraveled

## [YALB-375: Alerts](https://yaleits.atlassian.net/browse/YALB-375)

### Description of work
- Creates the alert component

### Testing Link(s)
- [ ] Navigate to the [Alert Story](https://deploy-preview-55--dev-component-library-twig.netlify.app/?path=/story/molecules-alert--alert)
- [ ] Navigate to the [Alert Examples](https://deploy-preview-55--dev-component-library-twig.netlify.app/?path=/story/molecules-alert--alert-examples)

### Functional Review Steps
- [ ] Interact with each of the alert types and verify everything works as expected (including across page reloads)
- [ ] Verify you can install alerts via the CLI

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

2022-03-30 21:58 UTC, ahitson commented
- Change alert titles to medium weight.
- Remove margin under titles when solo, reduce significantly when body text is there.
- Use grey 500 for the bar/divider.
- Center the right-side link/bar/button group vertically within the space.
- At smaller sizes the bar disappears putting the link by the button.
- When link moves under text on smaller sizes, add padding between it and the bottom of the alert box.
- The link was appearing by the chevron at small sizes or still showing when collapsed, should be hidden in the dropdown.
- Can we change the title on collapsed to overflow style (This is a titl...  X)
- The close and chevron need more target space around them. It'll also help balance things out on the smaller sizes.

2022-03-31 14:43 UTC, miketullo95 commented
everything functions perfectly! 👍  

one comment - The icons are aligned with the block of the text, but on smaller screens, it seems to get unaligned. 

![Screen Shot 2022-03-31 at 10 39 18 AM](https://user-images.githubusercontent.com/98550395/161081816-5f8de342-8dcd-4b31-97f9-663667d28e17.png)

2022-03-31 17:48 UTC, kara-franco requested changes
I love the alerts! Here's my accessibility feedback: 

- [x] `icon__decorative` variable needs to be set to hide icons (triangle, circle, "x" and arrows) from screen readers (currently "image" is being announced). 
- [x] Marketing Alert has an empty button (see image below). Add "Close Alert" to button.
- [ ] Focus indicator for arrows should be styled to match the respective focus indicator for links (see image below). 
- [ ] Second reset button is empty (see image below). 

Marketing Alert: 
<img width="787" alt="Screen Shot 2022-03-31 at 1 38 27 PM" src="https://user-images.githubusercontent.com/12991593/161117448-10272abc-76e2-4fa3-92ba-4dc5daeaa4b4.png">

Button Focus: 
<img width="67" alt="Screen Shot 2022-03-31 at 1 41 06 PM" src="https://user-images.githubusercontent.com/12991593/161117497-d777b460-f8c3-40ff-a152-23e06fee8f8d.png">

Empty Reset Button: 
<img width="688" alt="Screen Shot 2022-03-31 at 1 43 19 PM" src="https://user-images.githubusercontent.com/12991593/161117539-4f3a1959-b96a-484a-9e7e-2352fb19a370.png">

2022-04-01 10:22 UTC, ModulesUnraveled commented on components/02-molecules/alert/_alert.scss
> +.alert__heading {
Ashley had the same feedback. It's fixed now.

2022-04-01 10:41 UTC, ModulesUnraveled commented
@ahitson I think I've addressed everything according to our zoom call yesterday.

@miketullo95 On small screens, everything is top-aligned, so the text appears a little off from the icon because of the line-height of the text. On large screens everything is centered, so things may or may not line up depending on the content (see screenshot below)

@kara-franco Thanks for catching all of that. The `icon__decorative` thing almost makes me wonder if we should enable that by default...

<img width="1095" alt="Screen Shot 2022-04-01 at 5 39 14 AM" src="https://user-images.githubusercontent.com/1663810/161248010-69dda239-8f48-4ad7-b093-cfd5c3a50791.png">

2022-04-01 16:44 UTC, kara-franco commented
> https://deploy-preview-55--dev-component-library-twig.netlify.app

I agree, I think 95% of the time an icon will be decorative!

2022-04-01 17:37 UTC, kara-franco commented
Hmm, something is funky on my end when looking at Storybook: 

<img width="1180" alt="Screen Shot 2022-04-01 at 1 36 12 PM" src="https://user-images.githubusercontent.com/12991593/161314110-8e29a2e6-f496-4068-bc58-e0eff822ee29.png">

2022-04-01 17:43 UTC, ModulesUnraveled commented
@kara-franco That's a Netlify issue (that we should probably figure out). Basically, I added some new tokens to the tokens repo after the initial build in Netlify. Netlify tries to save time by using a cached `node_modules` directory, so it didn't get the new tokens. I just clicked the button to rebuild without cache, so it should look correct in a minute or so

2022-04-01 18:43 UTC, miketullo95 commented
> @miketullo95 On small screens, everything is top-aligned, so the text appears a little off from the icon because of the line-height of the text. On large screens everything is centered, so things may or may not line up depending on the content (see screenshot below)

Thanks for the info! Would it be possible to change the alignment on mobile so that the icon is center-aligned to the h2 first line text? On certain sizes its reads a little like a superscript. Let me know if that made sense lol. 

Thanks! 😄

2022-04-04 12:57 UTC, kara-franco approved these changes
Excellent, all fixes look great!

2022-04-04 16:24 UTC, ModulesUnraveled commented
@miketullo95 I worked with Ashley on the icon alignment (for both mobile and desktop) please check again.

@ahitson Please check as well

2022-04-04 16:41 UTC, miketullo95 approved these changes
icon looks great! 👍

2022-04-04 18:03 UTC, merged