YALB-419: Add Example Form to Storybook
yalesites-org/component-library-twig pull request #75
Opened 2022-04-20 16:06 UTC by ModulesUnraveled

## [YALB-419: Add Example Form to Storybook](https://yaleits.atlassian.net/browse/YALB-419)

### Description of work
- Creates a generic "Embed" component
- Embeds an example Qualtrics form and displays it on a page

### Testing Link(s)
- [ ] Navigate to the [Embed Story](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/molecules-embed--embed)
- [ ] Navigate to the [Qualtrics Page Example](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/page-examples-page-examples--qualtrics-page)

### Functional Review Steps
- [ ] Verify you can install the component with the CLI
- [ ] Verify the form appears in the embed

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

2022-04-21 17:41 UTC, kara-franco requested changes
Two question/thoughts below: 

The Embed title name should be required in Drupal. This will ensure that all embeds have accessible titles (helps screen reader users). 

Can we or should we name this component "Form Embed" to differentiate between the "Media Embed" which will have video/audio? 

Reference shot (title attribute): 
<img width="664" alt="Screen Shot 2022-04-21 at 1 27 57 PM" src="https://user-images.githubusercontent.com/12991593/164519271-051b978f-f1ab-465c-a4e3-ad0d15b42314.png">

2022-04-21 21:23 UTC, ModulesUnraveled commented
@kara-franco I agree. I'm assuming that we'll accept (and require) both the form (page) URL, and a title for the form (page). That way the title attribute will always be provided.

And I'm not sure about naming it "Form Embed"... there's nothing form-specific about it. It's actually just a generic iframe component at this point. And I don't know if we'll call the media ones "Media Embed", or if they'll just be called "Media" - or even "Video", "Audio", etc.

I think I'd be more inclined to call this component "Iframe" if anything, since that's really what it is. It doesn't support any other type of "embeds" that people might be used to.

2022-04-21 21:34 UTC, kara-franco commented
> @kara-franco I agree. I'm assuming that we'll accept (and require) both the form (page) URL, and a title for the form (page). That way the title attribute will always be provided.
> 
> And I'm not sure about naming it "Form Embed"... there's nothing form-specific about it. It's actually just a generic iframe component at this point. And I don't know if we'll call the media ones "Media Embed", or if they'll just be called "Media" - or even "Video", "Audio", etc.
> 
> I think I'd be more inclined to call this component "Iframe" if anything, since that's really what it is. It doesn't support any other type of "embeds" that people might be used to.

@ModulesUnraveled 
**Requiring page URL and title-** perfect!! 
**Name of Embed component-** that makes good sense! I think my gut reaction was if a developer came to Storybook looking for a form example- it may be hard to find. But, the way you are explaining it makes more sense. And, we will eventually have a Form component example (Subscribe or Contact Us) to reference. 

Thank you!!!

2022-04-21 21:35 UTC, kara-franco approved these changes

2022-04-21 22:20 UTC, ahitson commented
Is there a way to have the embed live in the space in full and not in a scrollable frame?

2022-04-21 22:30 UTC, ModulesUnraveled commented
@ahitson Unfortunately, no. The only way to embed Qualtics forms is in an iframe, and iframes don't have the ability (yet) to dynamically change size based on the content. So we just have to give it a fixed size (in this case, we're doing 70% of the screen height, so it's a little responsive, but still not perfect). Unfortunately, it's as good as we can get 😞

2022-04-22 21:09 UTC, ahitson approved these changes

2022-04-26 20:02 UTC, callinmullaney requested changes
@ModulesUnraveled This breaks down to mobile surprisingly well. See my code comment regarding the height... not sure if we should do something about it given this is iframed content that we have limited options with.

The border style between Chrome/FF is different for `<iframe>`. I think the iframe is just inheriting reset styles that should either be `border:0` or one of the existing border tokens explicitly. 
![Screenshot from 2022-04-26 14-47-49](https://user-images.githubusercontent.com/369018/165382554-7534c8bf-d01b-4166-a411-6182c9244c02.png)

2022-04-26 20:03 UTC, callinmullaney commented
Wow that screenshot sucks :shrug:

2022-04-26 20:56 UTC, ModulesUnraveled commented on components/02-molecules/embed/_embed.scss
> +  height: 70vh;
I think I'd rather not for now. We don't know what the content is going to be, and we can always adjust this once we get real forms starting to get entered. I'd hate to restrict it for now, and then find out that all of the forms are enormous, and we arbitrarily restricted the height, causing issues.

I'd like to leave it as flexible as possible for now, and then iterate if needed.

We might even end up giving people a "form size" option with "small", "medium", and "large" options that defines the max height... who knows?

2022-04-26 21:02 UTC, callinmullaney commented
@ModulesUnraveled one thing I forgot to mention is I think the iframe should be set as `display: block` looking at the page example there is a small gap between the iframe and wrapping `embed__inner`. See:
<img width="503" alt="Screen Shot 2022-04-26 at 4 01 04 PM" src="https://user-images.githubusercontent.com/369018/165391823-02f02b26-7ed8-4bf5-90a8-71b336cf8c12.png">

2022-04-26 21:11 UTC, ModulesUnraveled commented on components/02-molecules/embed/embed.twig
> +  class: bem(embed__base_class),
This is a prettier formatting thing. I think it's interpreting this as YML or something, which expects keys to be not in parentheses UNLESS the key has a dash in it... which we do... then the key MUST be in quotes.


UPDATE: I totally lied... the keys with dashes MUST have quotes, but the ones without can... and prettier isn't formatting twig... so I wonder if it's just something I brought over from working with the tokens and stuff...

...

I don't know if this was a conscious choice or just an artifact of development that just stuck... `class` works with, and without the quotes... So I think I'd rather have the quotes to keep things consistent (as far as color highlighting goes in my editor) but I also don't think we necessarily need to refactor every other component just to add the quotes...

I'll go ahead and add the quotes here, and if/when we update others make sure to add them in along the way.

2022-04-26 21:14 UTC, ModulesUnraveled commented
@callinmullaney I think I've addressed all of your feedback. I got Ashley to weigh in on the border, so we set that to be consistent across browsers.

2022-04-26 21:50 UTC, callinmullaney commented on components/02-molecules/embed/_embed.scss
> +  height: 70vh;
:+1:

2022-04-26 21:51 UTC, callinmullaney commented on components/02-molecules/embed/embed.twig
> +  class: bem(embed__base_class),
Sounds good. I figured it wasn't a big deal either but.

2022-04-26 21:52 UTC, callinmullaney approved these changes
Changes look good! :shipit:

2022-04-26 22:03 UTC, merged